/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/oOqLhpNBiEl
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuItem, DropdownMenuGroup, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { Textarea } from "@/components/ui/textarea"

export function Register() {
  return (
    <div key="1" className="flex items-center justify-center min-h-screen">
      <div className="flex flex-col mx-auto max-w-2xl space-y-6">
        <Card>
          <CardHeader>
            <div className="space-y-2 text-center">
              <h1 className="text-3xl font-bold">Event Organizer Registration</h1>
              <p>Fill out the form to list your event</p>
            </div>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="organizer-name">Organizer Name</Label>
                  <Input id="organizer-name" placeholder="Enter your name" required />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="email">Email</Label>
                  <Input id="email" placeholder="Enter your email" required type="email" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="organization-name">Organization Name</Label>
                  <Input id="organization-name" placeholder="Enter your organization's name" required />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="event-category">Event Category</Label>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button variant="outline">Select an event category</Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent className="w-56">
                      <DropdownMenuGroup>
                        <DropdownMenuItem>Conference</DropdownMenuItem>
                        <DropdownMenuItem>Seminar</DropdownMenuItem>
                        <DropdownMenuItem>Workshop</DropdownMenuItem>
                      </DropdownMenuGroup>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="event-date">Event Date</Label>
                  <Input id="event-date" required type="date" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="number-of-seats">Number of Seats</Label>
                  <Input id="number-of-seats" min="1" placeholder="Enter number of seats" required type="number" />
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="event-details">Event Details</Label>
                <Textarea className="min-h-[100px]" id="event-details" placeholder="Enter event details" required />
              </div>
              <div className="space-y-2">
                <Label htmlFor="more-details">Additional Details</Label>
                <Textarea className="min-h-[100px]" id="more-details" placeholder="Enter additional details" />
              </div>
              <Button className="w-full" type="submit">
                Submit
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
